<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="5718" started-at="2016-05-26T13:12:58Z" finished-at="2016-05-26T13:13:04Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5718" started-at="2016-05-26T13:12:58Z" finished-at="2016-05-26T13:13:04Z">
      <class name="QATools.QAMavenProject.TI_TestDragAndDropPage">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:QATools.QAMavenProject.TI_TestDragAndDropPage@7c16905e]" name="beforeSuite" is-config="true" duration-ms="7" started-at="2016-05-26T15:12:58Z" finished-at="2016-05-26T15:12:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="navigateToLogin()[pri:0, instance:QATools.QAMavenProject.TI_TestDragAndDropPage@7c16905e]" name="navigateToLogin" is-config="true" duration-ms="5168" started-at="2016-05-26T15:12:58Z" finished-at="2016-05-26T15:13:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateToLogin -->
        <test-method status="PASS" signature="goToDragAndDropPage()[pri:0, instance:QATools.QAMavenProject.TI_TestDragAndDropPage@7c16905e]" name="goToDragAndDropPage" is-config="true" duration-ms="335" started-at="2016-05-26T15:13:03Z" finished-at="2016-05-26T15:13:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goToDragAndDropPage -->
        <test-method status="FAIL" signature="testColumnAOverB()[pri:0, instance:QATools.QAMavenProject.TI_TestDragAndDropPage@7c16905e]" name="testColumnAOverB" duration-ms="198" started-at="2016-05-26T15:13:03Z" finished-at="2016-05-26T15:13:04Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [A] but found [B]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [A] but found [B]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at QATools.QAMavenProject.TI_TestDragAndDropPage.testColumnAOverB(TI_TestDragAndDropPage.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testColumnAOverB -->
        <test-method status="PASS" signature="afterEachTest()[pri:0, instance:QATools.QAMavenProject.TI_TestDragAndDropPage@7c16905e]" name="afterEachTest" is-config="true" duration-ms="6" started-at="2016-05-26T15:13:04Z" finished-at="2016-05-26T15:13:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterEachTest -->
        <test-method status="PASS" signature="afterTestSuite()[pri:0, instance:QATools.QAMavenProject.TI_TestDragAndDropPage@7c16905e]" name="afterTestSuite" is-config="true" duration-ms="347" started-at="2016-05-26T15:13:04Z" finished-at="2016-05-26T15:13:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTestSuite -->
      </class> <!-- QATools.QAMavenProject.TI_TestDragAndDropPage -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
